# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/crmbi/Comp541/projectA/projectA.cache/wt [current_project]
set_property parent.project_path C:/Users/crmbi/Comp541/projectA/projectA.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/crmbi/Comp541/projectA/projectA.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog C:/Users/crmbi/Comp541/projectA/projectA.srcs/sources_1/imports/Desktop/display640x480.sv
set_property file_type "Verilog Header" [get_files C:/Users/crmbi/Comp541/projectA/projectA.srcs/sources_1/imports/Desktop/display640x480.sv]
read_mem {
  C:/Users/crmbi/Comp541/projectA/projectA.srcs/sources_1/imports/Desktop/dmem_screentest.mem
  C:/Users/crmbi/Comp541/projectA/projectA.srcs/sources_1/imports/Desktop/bmem_screentest.mem
  C:/Users/crmbi/Comp541/projectA/projectA.srcs/sources_1/imports/Desktop/imem_screentest_nopause.mem
  C:/Users/crmbi/Comp541/projectA/projectA.srcs/sources_1/imports/Desktop/smem_screentest.mem
}
read_verilog -library xil_defaultlib -sv {
  C:/Users/crmbi/Comp541/projectA/projectA.srcs/sources_1/imports/sources_1/imports/sources_1/imports/new/fulladder.sv
  C:/Users/crmbi/Comp541/projectA/projectA.srcs/sources_1/imports/sources_1/imports/sources_1/imports/new/adder.sv
  C:/Users/crmbi/Comp541/projectA/projectA.srcs/sources_1/imports/sources_1/imports/sources_1/imports/new/shifter.sv
  C:/Users/crmbi/Comp541/projectA/projectA.srcs/sources_1/imports/sources_1/imports/sources_1/imports/new/logical.sv
  C:/Users/crmbi/Comp541/projectA/projectA.srcs/sources_1/imports/sources_1/imports/sources_1/imports/new/comparator.sv
  C:/Users/crmbi/Comp541/projectA/projectA.srcs/sources_1/imports/sources_1/imports/sources_1/imports/new/addsub.sv
  C:/Users/crmbi/Comp541/projectA/projectA.srcs/sources_1/imports/sources_1/imports/sources_1/imports/Desktop/register_file.sv
  C:/Users/crmbi/Comp541/projectA/projectA.srcs/sources_1/imports/sources_1/imports/sources_1/imports/new/ALU.sv
  C:/Users/crmbi/Comp541/projectA/projectA.srcs/sources_1/imports/new/xycounter.sv
  C:/Users/crmbi/Comp541/projectA/projectA.srcs/sources_1/imports/sources_1/new/dmem.sv
  C:/Users/crmbi/Comp541/projectA/projectA.srcs/sources_1/imports/sources_1/imports/sources_1/new/datapath.sv
  C:/Users/crmbi/Comp541/projectA/projectA.srcs/sources_1/imports/sources_1/imports/sources_1/imports/Desktop/controller.sv
  C:/Users/crmbi/Comp541/projectA/projectA.srcs/sources_1/new/bitmapmem.sv
  C:/Users/crmbi/Comp541/projectA/projectA.srcs/sources_1/imports/sources_1/new/vgatimer.sv
  C:/Users/crmbi/Comp541/projectA/projectA.srcs/sources_1/new/screenmem.sv
  C:/Users/crmbi/Comp541/projectA/projectA.srcs/sources_1/imports/Desktop/clockdiv.sv
  C:/Users/crmbi/Comp541/projectA/projectA.srcs/sources_1/imports/sources_1/imports/Desktop/mips.sv
  C:/Users/crmbi/Comp541/projectA/projectA.srcs/sources_1/new/memIO.sv
  C:/Users/crmbi/Comp541/projectA/projectA.srcs/sources_1/imports/sources_1/new/imem.sv
  C:/Users/crmbi/Comp541/projectA/projectA.srcs/sources_1/imports/sources_1/imports/Desktop/vgadisplaydriver.sv
  C:/Users/crmbi/Comp541/projectA/projectA.srcs/sources_1/imports/Desktop/top.sv
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/crmbi/Comp541/projectA/projectA.srcs/constrs_1/imports/Desktop/clock.xdc
set_property used_in_implementation false [get_files C:/Users/crmbi/Comp541/projectA/projectA.srcs/constrs_1/imports/Desktop/clock.xdc]

read_xdc C:/Users/crmbi/Comp541/projectA/projectA.srcs/constrs_1/imports/Desktop/vga.xdc
set_property used_in_implementation false [get_files C:/Users/crmbi/Comp541/projectA/projectA.srcs/constrs_1/imports/Desktop/vga.xdc]

read_xdc C:/Users/crmbi/Comp541/projectA/projectA.srcs/constrs_1/imports/Desktop/reset.xdc
set_property used_in_implementation false [get_files C:/Users/crmbi/Comp541/projectA/projectA.srcs/constrs_1/imports/Desktop/reset.xdc]


synth_design -top top -part xc7a100tcsg324-1


write_checkpoint -force -noxdef top.dcp

catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
